name: fti
dependencies:
  - python=3.7.3
  - pip
  - pip:
    - tensorflow
    - tensorflow-datasets
    - numba
    - numpy
    - scikit-learn
    - scikit-image
    - matplotlib
    - pandas
    - seaborn
    - umap-learn
    - tbb